### ISSUE TITLE
bug with name register task in file readme.md

### ISSUE THREAD

**Issue by AlexandrAnash** [MidlandHR/grunt-build-info-angular-injector#1]
At the moment:
Usage
grunt.initConfig({
  buildInfoAngularInjector: {
    module: 'my.angular.module',
    providerName: 'myBuildInfoProvider',
    target: 'src/buildInfoService.js'
  }
});

grunt.registerTask('default', ['buildInfoAngularInjector']);

I think you need to replace 'buildInfoAngularInjector' on 'injectBuildInfo'

**Comment by cleavera** [comment]
Just republished this with the latest readme thanks for pointing this out @AlexandrAnash

**Comment by AlexandrAnash** [comment]
and here grunt.registerTask('default', ['buildInfoAngularInjector']);

**Comment by cleavera** [comment]
My bad should have checked it again before publishing, republished with the full fix. Thanks @JonLambell for the fix and thanks @AlexandrAnash for contributing.
